import { db } from "@/lib/db";

/**
 * Matches Prisma's classic `cuid()` default: a lowercase "c" followed by 24
 * lowercase alphanumeric characters (25 chars total) — the shape of every
 * `NewsletterSubscriber.unsubscribeToken` value, whether it was generated by
 * `@default(cuid())` for a new row or backfilled by the engagement_compliance
 * migration for a pre-existing one. A candidate that doesn't match this
 * shape can never be a real token, so it's rejected before touching the
 * database (no point spending a lookup on an obviously-wrong value, and it
 * keeps the unsubscribe endpoint from being a place to fuzz arbitrary
 * strings against the DB).
 */
const UNSUBSCRIBE_TOKEN_PATTERN = /^c[a-z0-9]{24}$/;

export function isValidUnsubscribeToken(token: unknown): token is string {
  return typeof token === "string" && UNSUBSCRIBE_TOKEN_PATTERN.test(token);
}

function siteUrl(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL ?? "https://daakyka.com").replace(/\/$/, "");
}

/** Human-facing confirmation page — what the footer link in a marketing
 * email points at (RFC 8058 leaves the visible link free-form; only the
 * List-Unsubscribe header itself needs to be the direct one-click POST
 * target, see buildUnsubscribeApiUrl). */
export function buildUnsubscribeUrl(token: string): string {
  return `${siteUrl()}/unsubscribe?token=${encodeURIComponent(token)}`;
}

/** The direct API endpoint — this is what the `List-Unsubscribe` /
 * `List-Unsubscribe-Post` headers reference so a mail client can unsubscribe
 * with a single POST and no page load (RFC 8058 one-click). */
export function buildUnsubscribeApiUrl(token: string): string {
  return `${siteUrl()}/api/unsubscribe?token=${encodeURIComponent(token)}`;
}

export type UnsubscribeResult =
  | { ok: true; email: string; alreadyUnsubscribed: boolean }
  | { ok: false; error: string };

/**
 * Sets `unsubscribedAt` on the subscriber matching `token` (no-op if
 * already set) and cancels every currently-ACTIVE JourneyEnrollment for
 * that email — an unsubscribe should stop every future marketing touch,
 * not just the message the link came from.
 */
export async function unsubscribeByToken(token: string): Promise<UnsubscribeResult> {
  if (!isValidUnsubscribeToken(token)) {
    return { ok: false, error: "Invalid unsubscribe link" };
  }

  const subscriber = await db.newsletterSubscriber.findUnique({
    where: { unsubscribeToken: token },
  });
  if (!subscriber) {
    return { ok: false, error: "Invalid unsubscribe link" };
  }

  const alreadyUnsubscribed = Boolean(subscriber.unsubscribedAt);
  if (!alreadyUnsubscribed) {
    await db.newsletterSubscriber.update({
      where: { id: subscriber.id },
      data: { unsubscribedAt: new Date() },
    });
  }

  await db.journeyEnrollment.updateMany({
    where: { email: subscriber.email, status: "ACTIVE" },
    data: { status: "CANCELLED", nextRunAt: null, lockedAt: null },
  });

  return { ok: true, email: subscriber.email, alreadyUnsubscribed };
}
